Use absolute value of hash as bucket
timtadh/data-structures pull request #12
Opened 2022-04-29 13:25 UTC by jrisc

On 32 bits architechtures, string hashes tend to have negative values.
Such values cannot be used as bucket identifiers for hashtables:
```
github.com/timtadh/data-structures/hashtable
--- FAIL: TestPutHasGetRemove (0.00s)
panic: runtime error: index out of range [-9] [recovered]
        panic: runtime error: index out of range [-9]
```

Using absolute value in case of negative hash solves this issue.

2022-07-15 04:53 UTC, timtadh requested changes

2022-07-15 04:53 UTC, timtadh commented on hashtable/hashtable.go
> +	return abs(key.Hash() % len(self.table))
```suggestion
	return abs(key.Hash()) % len(self.table)
```

2022-07-18 08:05 UTC, jrisc commented on hashtable/hashtable.go
> +	return abs(key.Hash() % len(self.table))
It makes more sense this way indeed.

2022-07-18 08:15 UTC, merged

2022-07-18 08:22 UTC, timtadh commented
1. Thank you so much for your bug fixes
2. I pushed a tag for this fix at `v0.6.2`